alphabet = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
            'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
characters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
            'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '#', '+']
key = ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']
match = ['0', '0', '0', '0', '0', 'Z', 'X', '0', '0', '0', '0', 'V', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'K', '0']


blocks = []

cipher = 0
plain = 0
pos = 0
failed = False


ciphertext = 'VXLKVZXZSZXODRQYFQEMOLMRTOFATIMXTAWAYANKRBPCESXCUPOB#RTBXSEKRDSJ+WYTG+JDIKPNRJTP#AFYXBAZROVAWUHRUYIZRCOSXCBNW#VNIQSXJPEUYKCJOPSMCEQXBIC#HYIZT+RBJ+MXPMTDSKRUNQ#UBIHZXVBZETEGSZEMWXQDUFQXSEKRZDENONDSZEQUIXNGL+REONAHUOQ+ULFNELDQBHKZGSQPSMCNRQ#OLMEOPFXLBULSY#IC+IO#SGRDLVIMFUMPOTLUPADTSCAUWMSJGXVHWAHCIWBNKAPIZEMWPXDBLCP+H#KNRJTPZELNZAWZRKSHKNDSLHJNKVFQHMO#ATLSPISEJFSTDSPQYQFQEGZHLNDXZ+VKB+JKSDFWZATUXH#KM#XNHXHZTLUKBTEBWDPU#APXBPOTGZCHODTSQGNBJ#IVUVMZXV+PFANTRILPEMHYOERKART+YDJWOIHUIZFTXLWUB+ZGSLNQYT+R+THCHTPBXZJVLDTEIWIHKNDA#IQYCLWJVMOPWRFTGKXCQEHCNHMBEQ+MPUCODSOLDJWKSHKNDA#ILUXVTOCHCKUVQRFBXJTAZAKUFHIYTBJNMCHSOXLXYJKMZJWMDUGNWPBWYRXISFULYNTBZWZKTYGRY+RQVH#SW#QBFYXW+WZSIASTI+VRGPXQMXEVUKQXJGNIXBGHEWYIYWYSXBL+JWGZCHOQHZWLXQBHVJZSDKWRGFTUGXTGW#MEOTNTEJAQH#JEAJWRQGVKYXN#LOZWUZTWPHWXBMPT+DLVZXJHIONATEUQOSRDLWYR+CPVQENQMENKXZ+UBXKSMTOJWMI+SUJNDJMXI#HPMEOWUXYJZXJPMIKRZIQCXBO#HYAIFDUVQKUBNHYVHWPRBTCJ+MPORQVNEGIVXYJKCRUIZQDIHPJVLUIVGJBVXYWSQNH#VYQCJPVMGOQFMNCKXFLDTSGRASRHWC#FOFAVLNBIFHNELJBNHYEMIAPSMCJPYIWQJHVCWDURFBRTBNBJAUKW+ASVCNDJM+BPM#PLJHLNVZLUPAXPR+HNLR+DIVHGPASPBNUHFOIHPZTYXNS+QA#VD+BPHGLEQROFXQRNYDFSFJOIXAI+QEIEMEOTXLNJBZWSGSFAXUOQFP+MQPHULTEGHPZTHBJKTKVNHMBEQEIEKVUSEFLPJHOK#TDIARYFQPBOCPOWSROENQIJ+WCJZTRWOAX+YFQPBOCPOW#ANPIXALTVWKSHXQMCENGMEOHUQPXBEROCKCR+VQSPIVNQLBAINWILDT#DRHKOXWDRXIWCPCUCPCUFYJBWHQXYPER+GA#INQPBOCPOWHZTXTPZMWYWSVJA#YFQSH#XEUOCJFULROEILZIJZXODHOAX+WMT+ZQG+SRUGPQHRNLDTCRNISRYTDLVGWXH#SCKUNENUKTJKPAWIXJSV#KMEN#TQWIXBJ+WKJWOXMDLGVPWKCKUENUIPGJRWMKNPRDHWDLPBOCPOW#JQTEGB+EJSHWAYTQYCLWAHVLSORSUZXNJ+BTESGRASRXMQX+SCTPMULNYDHFOVKSYCJDRQNFYFW+DHXVHWLYWYQLXYJZXJEQUI+LXMQSI#XMHCTOB#TYH#NIXJHY#H#NYI#V+IVGZCHOW#QBTILDTGNEVZDSJLHIJMINR+UIFLJM#OWRFYX+ZSOJPUKCQYDLVTZWOQTNCUQDLDTVJWU+LQFPGQPXVBZDHRFVBLB+JPVYDXDYWMISVWAPCJSCILJHFYLDTZGXK#SZDMXUWTC+BPECUIOWAQWKGCQSNDSAWOHMYWMIRC+BPMRCNZDURFBRTBNHYOCKCRYTOQGXKXMCKPWRNQRXKJTIXD+NITRUWDQPFPU#NBNUTEGZTSODHKYHIYWTCBOCAH#CIXNXVHEYXPMHKNDA#IZQ#HUXVCKNATBNTZGKSWQMUTRCPMPUSOW#ANKUOTYXMUNLYFP+TWBYPULRSOKA+WZSIYDWYQESFJVCOPB#HVNLPCTSRPSCASGYFQ+BIMKYBNW#HZXBXSVXYJRNGLUXISFULYZIWRV+HPZSYJPEUYJFSYWNMSTJVDZUFVTANO#EMWAXHI+RCHE+OFOHRA#ANGXHPYXETU+AXRQ+WSMPAHCNPZU+OPJNTVOCKCRVI+RHFOFANQLEO+UTESXKWPJADPDLV#GZQJSKISE+MXSZESNYKWL#XHIYQGIEMEOFUHRTESNISECAKSHW+IRYFQC#SMQJQSWAQWKGCTZWNSDJ+A#SU+QIHMKJMRFTOQSRFKXSBJXEKNVXODJEVGPCIPBUFYXHPQBTGMSRASAIDPGQPMSAIF#ANVZXZSZXODLHYDLVKPRWBP#HQEHIVZGRYDRGUWJU#+H#PWTSZTXFTKAQNZJPCUAKVNYRVNJ#TJMRFAPFW#HZQL+NBLPEZTBJYEUPYRGIJHBGSRAVSFSBFOENB+JOASAIASXMTCPVGZHXFUTKUQTIGRKJO#VGMV#QFPSCILWUXVKMIJUVHKGRVYQCJESXAMCKXFLDUQRSVWYRWKNFHV+NDJM+BPCHVSNFHRHLDSZEMWBDWDRXBVWGH#BVNELHSREAQAXDIPVLH#OHORQVQ+JBNHYQTKCA#ILULGVMKQGVYPBOFYXRHED#LWAPRIMDLVIMKNVLHUVBOBXSACOVAHMHUYVNR+ITAWCLSCIL#ANVKYRQRQAXIMNUGVGZUCTONTELZIYRPVYDMVMD+BPRVSCIDLTWB+JUTDKNQHV+DLVUHULBI#JHZTEGB+NVAKUMRQDOR#FAPMEOLFQ#VTSZXODKCQYIMNUGVTGZUC#AHRSOKA+WAYW+OAX+YFQMFOFLPBO+OFUQNHYMIOLRYI+SI#PACKXFAJKISERMXKPEQT+GBRYFQJM+IWOLFVHK#YQLFYXSZERWXIOSYQTRCPIKPJXVCKXZNWHPHYPEUYKCRPNUIQPJMCKXFJVRQKDTKJ+AXYHTDQHWTGWUC#XNPFYXTCUVDFOAIVWNDJGH#KONBUS+VKQNZJPUYW+SGRPVJGMQAR#NZIZULDTZGRNWOFXDTUGZSMGZORQHZUJUZEWX#HOAX+YFQXNC#R#C#UTPIQ+HQD#HWAH+CTJRSXMFIW#RTLB+JERASRYNRCHE+OFOHRA#ANJBZWSNPUKCQYPTUVH#RWLP#QLURJZMOHBJUSDKOQGBJPWVOEQFUBNWRNIQOJYEU#A#INQPXCVCXW#QBDVAYHIXYJKCRX+I+P+ISFMEOWX+QFTUXBTWUPHCNHMB+QCEVYGRJW#QUXB+JKQTKCA#INUMCWCMCOXVRTLB+JGONWNFYFQ#JPOLWCMSHFSBZXJ+NJMXYPUPA#TVCZJ#TGW#UJDIXFSOKAQBSACFQAX+WVWOSXOLBJLXFLDZTJMOKEIHWKRG#PCNHMUJHUIZ+WUB+WMR+GBVQS+QCEVYGRJWQDVKTZGXKESW+NGYFQ+BIMGPHLCKJANELDTVJRARCO#XOCZLH+PAVOD+VWKQBHKROVQT+G+RIZ+SVUVLNUNURILPSCHWEWIDQBMITBPOC#XPBOJVRJAYHQEKNTIQ+IGJMRFCKULNJZTBJKINI+VFSUFWMIDVTJHBSPB#AHREXUX+#OVACNXBPCENPCHUIVPXKMVZJR+J+WXMQHZGPCMEOILULTLUPAVZOATKXSRFDBVPLBOWRIXJQKSKCQYTE+HI#QFPRBUHZT+FJKJT+HIJZSAVWXHUYBTQDVMUMEVLHJUXJKBHKEJZSDKOHUGRPISFVLNYCXZXNV+B+JOASAIASXMNDJMIEMEVSQHRIUPAVQSWSWLUYFQCIGNQLBDOIZKSJHSZESANFBPOTAPEWCHCKUSTBMXNUKQSACIUPYA#DIQPSRCUAHSPBEQEGPAIXD+YGQPVQ+UVRHFMWBOPBNQVBGUKSZXYJUPYSGYIC#IVHLUOUYDVBLQCT+NACJYSNQGSGINX+SCNPZUMO+UNEWJBJ+NATRDFGSUYIMRCQHU#OASEKS+PZQNTYPEMIAYFQJMVMOMVRBNQWKGDSBJFSW+IXJG+JWQJHYXZ+JQSEJPV+KNFYFTNQV#JXQCVOWJUATFXMNVSOZSAWLVMQUGW#JHUFUFTUXKJRNYOQDU+MPZH+BPUO#IZJPMPQVPEUYVWCQAIEQV#XFUYBO#QOE+UABEWESKCJOWDTUMKXMVCPWPZQSELDSZEMWGRVBI+RXTWIOIZNWUB+ZGSTDJASVCLH#KMEN#FYXWSEJERXJ+WYFQ#VOKWLSPOZTKIUKBTYDTSRGQINDJM+BPZHNYIYFYXJHQYESAJ+ARMCRQPFOHDFXZXYRQTVZGSRNLRGVJQMVOCBNBDSNWUAY#JURXJ+WIYQGOVZEWCMCIDHRXVFXZ+JKTFW+ASYPNDJMUBIFPMEODUXKJZSZXODU#PQDVMZ+BPAHSCFSNFOVKPGZGSAF#OVUYIJPGVGZHUOB#LTKNPSYVOCKCJOX+I+P+ISFMEOZIZ+VKBEXRDSGRHWC#KVRPNCIUZRWBUKXWMDOQU#CJW#NOVCR+OI#GPLBPONETXBHXYCUAXNHDZP+GLHFZXZRILPERNZGOVKA#IW+VJWRTLPNTLUPAVIJQT+GBROMPE#VGWIRBHFVBMZNZXPMYGQGUG#HPI#VPOFVTEANBJPRKP+GIVQXTOCN#PWPRFVZUGZGSAWJOQGPQFPCPVGZUCQUVGNBIPGROVASYXOGVJNFKYHUXBFWBXMWY#TDKWYDTIHGPACKUZJVRQ+HQD#ILQGBTC+BPJUYRCNHUQBNBJBNHYRDFYRYO+C+SGQCFP#GWDXZQBHKAKUKWIYWMI+BPQAHLCP#TQDLDTZKTI+WMIWNJZEU#HFUTLXZYHYJKWYTWJGJG+H#HPMRJWRFVZWXJWYCTDFNA#I+OPOTGW#CRMIPNLDTIWKFPAPRHTU#EZI#KQMIR#ODHD+UJQDEKNRGUO+Q+BOMXHUXZSOEUBRNZGOVKI+RYHT+WJZOVHLCWHZFYXJWATKIGOAX+YFQSITJVRBJHEKMXZTXWK#SFQUVNUVPVTJRBEJO+RTSRDSHQDVMDQVGZHV#SNAUFJILPEBHXYWAWQUIDLVTPOJFHFJV+B+JDODFNGY+RH#VLHVCPWNLWXOJAB+WEKCRQCTVWPICZH#YOCHXNJKMZGSIOUTVRHGPAUIDUGVPUVKSIRCNHDCTCESFUPOB#RILPEB+J#SEJIRQPC#SGAPUBZIJU+LPGWD+J+AXIMQSOBOFASNBDFYOIHIVZ#JEMWAX+G+RJGIGUJMRFPYJVRJZTSRYKPYRBDLV#GZHUIDUGVPUSODKIJ+SGRDLVRPNSCI#ANTUE+JKNPOABRBINDGSUPASCILHFOIEZNAZJ#U+O+IVRHFCO#H#CKXFIDPIYCJRHJGVLSUNJF+PYJ#HFXJKSYVOFSTDSRUYIZRZ#POHSWXLJILPER+JYVHJ+WYFQSHPBI#PMUQONTBXBHJKRHWA#IVRMBPCUBFKX+UFTDLXZIVJRDFAXBICQ+VGZHQOTYLVHB+JWUFWBXTW+SPFJT#O#ATLKPHYSPORUYFQXHWPIHX#JHXNILPEB+NVIXD+IGOXDIZNPVGZH#PWPQDLDTUJISFIS+FQGZOLBPBOHZFVXKTORGRDFOUYTGRZHUFCJFUTZETWKPTNXSGIMD+BPFTSOIZNV+B+JPMIDRBVLHMVHSCIDURFBPWZGSFWKSQIG+QBVMOALNYJFTHZUOLBHTSKCRDHWDL+BPOENFONLPNASKSIORYFQEVTGCTOCPCUBVWXZSACURXWJA#V+ZQG+SMPORBW#LWXLQBHKJZSAQNGIWMDLVWS+PRHLCTPZEGNZBJWNATCUAQNHDUOQVQXTOFAXISLXVRZSXJRDFIXJSIGRHLC#QFYX+SZGSAGQGBOR#FAP#CUVSODYQLNFXZQBHKROVRAWQGWMNMIMOMVRB#QWIJAYVZOAQTHCJ+WPTU#NPRQFMEOAPBXEBYJQTHMEMWNDRDVDRJ#TGW#NRJFWSZXKXRNYGS+N'
plaintext = 'tentialstopthetripwireoptionisalsodeprecatedsinceitismorelikelythattheexpl'

#ciphertext = 'VXLKVZX'
#plaintext =  'lincoln'

def go(_list_, index, aim):
    num = 0
    while index % len(_list_) != aim:
        index += 1
        num += 1
    return num

def get_key(ciphertext, plaintext):
    global num, key, pos, plain, cipher, failed
    for each in range(len(ciphertext)):
        thing = go(alphabet, plain, alphabet.index(plaintext[each].lower()))
        if thing == 0:
            thing = 26
        #print(cipher, plain, thing)
        plain = (plain + thing) % 26
        cipher = (cipher + thing) % 28
        #print(cipher, plain, thing)
        if key[cipher] == '0' and ciphertext[each] not in key:
            key[cipher] = ciphertext[each]
    pos += 1
    for each in key:
        if each == '0':
            failed = True
    if failed != True:
        print(key, pos)
    failed = False
    key = ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']

for letter in range(len(ciphertext) - (len(plaintext) - 1)):
    blocks.append(ciphertext[letter:letter + len(plaintext)])

print(len(blocks))

for block in range(len(blocks)):
    get_key(blocks[block], plaintext)

