alphabet = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
key = ['A', 'H', 'K', 'P', 'E', 'V', 'Z', 'Q', 'B', 'I', 'L', 'R', 'F', 'W', '#', 'S', 'C', 'J', 'M', 'T', 'G', 'X', '+', 'N', 'D', 'U', 'Y', 'O']
frequencies = [8.55, 1.60, 3.16, 3.87, 12.10, 2.18, 2.09, 4.96, 7.33, 0.22, 0.81, 4.21, 2.53, 7.17, 7.47, 2.07, 0.10, 6.33, 6.73, 8.94, 2.68, 1.06, 1.83, 0.19, 1.72, 0.11]

num = -2
letter = 0

def go(_list_, index, aim):
    num = 0
    while index % len(_list_) != aim:
        index += 1
        num += 1
    return num

def string(_list_):
    string = ''
    for each in _list_:
        string += str(each)
    return string

def decode(text):
    global num
    text = [str(x) for x in str(text)]
    letters = []
    for each in text:
        if each.upper() in key:
            thing = go(key, num, key.index(each.upper()))
            num += thing
            #print(num)
            letters.append(alphabet[num % 26].upper())
        else:
            letters.append(each)
    print(string(letters))

for each in key:
    key = [str(x) for x in str(string(key)[1:]+each)]
    decode('VXLKVZXZSZXODRQYFQEMOLMRTOFATIMXTAWAYANKRBPCESXCUPOB#RTBXSEKRDSJ+WYTG+JDIKPNRJTP#AFYXBAZROVAWUHRUYIZRCOSXCBNW#VNIQSXJPEUYKCJOPSMCEQXBIC#HYIZT+RBJ+MXPMTDSKRUNQ#UBIHZXVBZETEGSZEMWXQDUFQXSEKRZDENONDSZEQUIXNGL+REONAHUOQ+ULFNELDQBHKZGSQPSMCNRQ#OLMEOPFXLBULSY#IC+IO#SGRDLVIMFUMPOTLUPADTSCAUWMSJGXVHWAHCIWBNKAPIZEMWPXDBLCP+H#KNRJTPZELNZAWZRKSHKNDSLHJNKVFQHMO#ATLSPISEJFSTDSPQYQFQEGZHLNDXZ+VKB+JKSDFWZATUXH#KM#XNHXHZTLUKBTEBWDPU#APXBPOTGZCHODTSQGNBJ#IVUVMZXV+PFANTRILPEMHYOERKART+YDJWOIHUIZFTXLWUB+ZGSLNQYT+R+THCHTPBXZJVLDTEIWIHKNDA#IQYCLWJVMOPWRFTGKXCQEHCNHMBEQ+MPUCODSOLDJWKSHKNDA#ILUXVTOCHCKUVQRFBXJTAZAKUFHIYTBJNMCHSOXLXYJKMZJWMDUGNWPBWYRXISFULYNTBZWZKTYGRY+RQVH#SW#QBFYXW+WZSIASTI+VRGPXQMXEVUKQXJGNIXBGHEWYIYWYSXBL+JWGZCHOQHZWLXQBHVJZSDKWRGFTUGXTGW#MEOTNTEJAQH#JEAJWRQGVKYXN#LOZWUZTWPHWXBMPT+DLVZXJHIONATEUQOSRDLWYR+CPVQENQMENKXZ+UBXKSMTOJWMI+SUJNDJMXI#HPMEOWUXYJZXJPMIKRZIQCXBO#HYAIFDUVQKUBNHYVHWPRBTCJ+MPORQVNEGIVXYJKCRUIZQDIHPJVLUIVGJBVXYWSQNH#VYQCJPVMGOQFMNCKXFLDTSGRASRHWC#FOFAVLNBIFHNELJBNHYEMIAPSMCJPYIWQJHVCWDURFBRTBNBJAUKW+ASVCNDJM+BPM#PLJHLNVZLUPAXPR+HNLR+DIVHGPASPBNUHFOIHPZTYXNS+QA#VD+BPHGLEQROFXQRNYDFSFJOIXAI+QEIEMEOTXLNJBZWSGSFAXUOQFP+MQPHULTEGHPZTHBJKTKVNHMBEQEIEKVUSEFLPJHOK#TDIARYFQPBOCPOWSROENQIJ+WCJZTRWOAX+YFQPBOCPOW#ANPIXALTVWKSHXQMCENGMEOHUQPXBEROCKCR+VQSPIVNQLBAINWILDT#DRHKOXWDRXIWCPCUCPCUFYJBWHQXYPER+GA#INQPBOCPOWHZTXTPZMWYWSVJA#YFQSH#XEUOCJFULROEILZIJZXODHOAX+WMT+ZQG+SRUGPQHRNLDTCRNISRYTDLVGWXH#SCKUNENUKTJKPAWIXJSV#KMEN#TQWIXBJ+WKJWOXMDLGVPWKCKUENUIPGJRWMKNPRDHWDLPBOCPOW#JQTEGB+EJSHWAYTQYCLWAHVLSORSUZXNJ+BTESGRASRXMQX+SCTPMULNYDHFOVKSYCJDRQNFYFW+DHXVHWLYWYQLXYJZXJEQUI+LXMQSI#XMHCTOB#TYH#NIXJHY#H#NYI#V+IVGZCHOW#QBTILDTGNEVZDSJLHIJMINR+UIFLJM#OWRFYX+ZSOJPUKCQYDLVTZWOQTNCUQDLDTVJWU+LQFPGQPXVBZDHRFVBLB+JPVYDXDYWMISVWAPCJSCILJHFYLDTZGXK#SZDMXUWTC+BPECUIOWAQWKGCQSNDSAWOHMYWMIRC+BPMRCNZDURFBRTBNHYOCKCRYTOQGXKXMCKPWRNQRXKJTIXD+NITRUWDQPFPU#NBNUTEGZTSODHKYHIYWTCBOCAH#CIXNXVHEYXPMHKNDA#IZQ#HUXVCKNATBNTZGKSWQMUTRCPMPUSOW#ANKUOTYXMUNLYFP+TWBYPULRSOKA+WZSIYDWYQESFJVCOPB#HVNLPCTSRPSCASGYFQ+BIMKYBNW#HZXBXSVXYJRNGLUXISFULYZIWRV+HPZSYJPEUYJFSYWNMSTJVDZUFVTANO#EMWAXHI+RCHE+OFOHRA#ANGXHPYXETU+AXRQ+WSMPAHCNPZU+OPJNTVOCKCRVI+RHFOFANQLEO+UTESXKWPJADPDLV#GZQJSKISE+MXSZESNYKWL#XHIYQGIEMEOFUHRTESNISECAKSHW+IRYFQC#SMQJQSWAQWKGCTZWNSDJ+A#SU+QIHMKJMRFTOQSRFKXSBJXEKNVXODJEVGPCIPBUFYXHPQBTGMSRASAIDPGQPMSAIF#ANVZXZSZXODLHYDLVKPRWBP#HQEHIVZGRYDRGUWJU#+H#PWTSZTXFTKAQNZJPCUAKVNYRVNJ#TJMRFAPFW#HZQL+NBLPEZTBJYEUPYRGIJHBGSRAVSFSBFOENB+JOASAIASXMTCPVGZHXFUTKUQTIGRKJO#VGMV#QFPSCILWUXVKMIJUVHKGRVYQCJESXAMCKXFLDUQRSVWYRWKNFHV+NDJM+BPCHVSNFHRHLDSZEMWBDWDRXBVWGH#BVNELHSREAQAXDIPVLH#OHORQVQ+JBNHYQTKCA#ILULGVMKQGVYPBOFYXRHED#LWAPRIMDLVIMKNVLHUVBOBXSACOVAHMHUYVNR+ITAWCLSCIL#ANVKYRQRQAXIMNUGVGZUCTONTELZIYRPVYDMVMD+BPRVSCIDLTWB+JUTDKNQHV+DLVUHULBI#JHZTEGB+NVAKUMRQDOR#FAPMEOLFQ#VTSZXODKCQYIMNUGVTGZUC#AHRSOKA+WAYW+OAX+YFQMFOFLPBO+OFUQNHYMIOLRYI+SI#PACKXFAJKISERMXKPEQT+GBRYFQJM+IWOLFVHK#YQLFYXSZERWXIOSYQTRCPIKPJXVCKXZNWHPHYPEUYKCRPNUIQPJMCKXFJVRQKDTKJ+AXYHTDQHWTGWUC#XNPFYXTCUVDFOAIVWNDJGH#KONBUS+VKQNZJPUYW+SGRPVJGMQAR#NZIZULDTZGRNWOFXDTUGZSMGZORQHZUJUZEWX#HOAX+YFQXNC#R#C#UTPIQ+HQD#HWAH+CTJRSXMFIW#RTLB+JERASRYNRCHE+OFOHRA#ANJBZWSNPUKCQYPTUVH#RWLP#QLURJZMOHBJUSDKOQGBJPWVOEQFUBNWRNIQOJYEU#A#INQPXCVCXW#QBDVAYHIXYJKCRX+I+P+ISFMEOWX+QFTUXBTWUPHCNHMB+QCEVYGRJW#QUXB+JKQTKCA#INUMCWCMCOXVRTLB+JGONWNFYFQ#JPOLWCMSHFSBZXJ+NJMXYPUPA#TVCZJ#TGW#UJDIXFSOKAQBSACFQAX+WVWOSXOLBJLXFLDZTJMOKEIHWKRG#PCNHMUJHUIZ+WUB+WMR+GBVQS+QCEVYGRJWQDVKTZGXKESW+NGYFQ+BIMGPHLCKJANELDTVJRARCO#XOCZLH+PAVOD+VWKQBHKROVQT+G+RIZ+SVUVLNUNURILPSCHWEWIDQBMITBPOC#XPBOJVRJAYHQEKNTIQ+IGJMRFCKULNJZTBJKINI+VFSUFWMIDVTJHBSPB#AHREXUX+#OVACNXBPCENPCHUIVPXKMVZJR+J+WXMQHZGPCMEOILULTLUPAVZOATKXSRFDBVPLBOWRIXJQKSKCQYTE+HI#QFPRBUHZT+FJKJT+HIJZSAVWXHUYBTQDVMUMEVLHJUXJKBHKEJZSDKOHUGRPISFVLNYCXZXNV+B+JOASAIASXMNDJMIEMEVSQHRIUPAVQSWSWLUYFQCIGNQLBDOIZKSJHSZESANFBPOTAPEWCHCKUSTBMXNUKQSACIUPYA#DIQPSRCUAHSPBEQEGPAIXD+YGQPVQ+UVRHFMWBOPBNQVBGUKSZXYJUPYSGYIC#IVHLUOUYDVBLQCT+NACJYSNQGSGINX+SCNPZUMO+UNEWJBJ+NATRDFGSUYIMRCQHU#OASEKS+PZQNTYPEMIAYFQJMVMOMVRBNQWKGDSBJFSW+IXJG+JWQJHYXZ+JQSEJPV+KNFYFTNQV#JXQCVOWJUATFXMNVSOZSAWLVMQUGW#JHUFUFTUXKJRNYOQDU+MPZH+BPUO#IZJPMPQVPEUYVWCQAIEQV#XFUYBO#QOE+UABEWESKCJOWDTUMKXMVCPWPZQSELDSZEMWGRVBI+RXTWIOIZNWUB+ZGSTDJASVCLH#KMEN#FYXWSEJERXJ+WYFQ#VOKWLSPOZTKIUKBTYDTSRGQINDJM+BPZHNYIYFYXJHQYESAJ+ARMCRQPFOHDFXZXYRQTVZGSRNLRGVJQMVOCBNBDSNWUAY#JURXJ+WIYQGOVZEWCMCIDHRXVFXZ+JKTFW+ASYPNDJMUBIFPMEODUXKJZSZXODU#PQDVMZ+BPAHSCFSNFOVKPGZGSAF#OVUYIJPGVGZHUOB#LTKNPSYVOCKCJOX+I+P+ISFMEOZIZ+VKBEXRDSGRHWC#KVRPNCIUZRWBUKXWMDOQU#CJW#NOVCR+OI#GPLBPONETXBHXYCUAXNHDZP+GLHFZXZRILPERNZGOVKA#IW+VJWRTLPNTLUPAVIJQT+GBROMPE#VGWIRBHFVBMZNZXPMYGQGUG#HPI#VPOFVTEANBJPRKP+GIVQXTOCN#PWPRFVZUGZGSAWJOQGPQFPCPVGZUCQUVGNBIPGROVASYXOGVJNFKYHUXBFWBXMWY#TDKWYDTIHGPACKUZJVRQ+HQD#ILQGBTC+BPJUYRCNHUQBNBJBNHYRDFYRYO+C+SGQCFP#GWDXZQBHKAKUKWIYWMI+BPQAHLCP#TQDLDTZKTI+WMIWNJZEU#HFUTLXZYHYJKWYTWJGJG+H#HPMRJWRFVZWXJWYCTDFNA#I+OPOTGW#CRMIPNLDTIWKFPAPRHTU#EZI#KQMIR#ODHD+UJQDEKNRGUO+Q+BOMXHUXZSOEUBRNZGOVKI+RYHT+WJZOVHLCWHZFYXJWATKIGOAX+YFQSITJVRBJHEKMXZTXWK#SFQUVNUVPVTJRBEJO+RTSRDSHQDVMDQVGZHV#SNAUFJILPEBHXYWAWQUIDLVTPOJFHFJV+B+JDODFNGY+RH#VLHVCPWNLWXOJAB+WEKCRQCTVWPICZH#YOCHXNJKMZGSIOUTVRHGPAUIDUGVPUVKSIRCNHDCTCESFUPOB#RILPEB+J#SEJIRQPC#SGAPUBZIJU+LPGWD+J+AXIMQSOBOFASNBDFYOIHIVZ#JEMWAX+G+RJGIGUJMRFPYJVRJZTSRYKPYRBDLV#GZHUIDUGVPUSODKIJ+SGRDLVRPNSCI#ANTUE+JKNPOABRBINDGSUPASCILHFOIEZNAZJ#U+O+IVRHFCO#H#CKXFIDPIYCJRHJGVLSUNJF+PYJ#HFXJKSYVOFSTDSRUYIZRZ#POHSWXLJILPER+JYVHJ+WYFQSHPBI#PMUQONTBXBHJKRHWA#IVRMBPCUBFKX+UFTDLXZIVJRDFAXBICQ+VGZHQOTYLVHB+JWUFWBXTW+SPFJT#O#ATLKPHYSPORUYFQXHWPIHX#JHXNILPEB+NVIXD+IGOXDIZNPVGZH#PWPQDLDTUJISFIS+FQGZOLBPBOHZFVXKTORGRDFOUYTGRZHUFCJFUTZETWKPTNXSGIMD+BPFTSOIZNV+B+JPMIDRBVLHMVHSCIDURFBPWZGSFWKSQIG+QBVMOALNYJFTHZUOLBHTSKCRDHWDL+BPOENFONLPNASKSIORYFQEVTGCTOCPCUBVWXZSACURXWJA#V+ZQG+SMPORBW#LWXLQBHKJZSAQNGIWMDLVWS+PRHLCTPZEGNZBJWNATCUAQNHDUOQVQXTOFAXISLXVRZSXJRDFIXJSIGRHLC#QFYX+SZGSAGQGBOR#FAP#CUVSODYQLNFXZQBHKROVRAWQGWMNMIMOMVRB#QWIJAYVZOAQTHCJ+WPTU#NPRQFMEOAPBXEBYJQTHMEMWNDRDVDRJ#TGW#NRJFWSZXKXRNYGS+N')
